ALTER TABLE agil_configuracion_contable_comprobante drop tipo_comprobante;
ALTER TABLE agil_configuracion_contable_comprobante drop glosa_debe;
ALTER TABLE agil_configuracion_contable_comprobante drop glosa_haber;
ALTER TABLE agil_sucursal_actividad_dosificacion drop cuenta;
ALTER TABLE agil_proforma drop asiento_contabilidad;